### ISSUE TITLE
How to stop a signal?

### ISSUE THREAD

**Issue by onetonfoot** [TsurHerman/Signals.jl#8]
Hey thanks for the package. I was wondering how do I stop a signal once it's been created, something like? 

```julia
A = Signal(1)

B = Signal(A) do x
    x * 2
end

C = Signal(B) do x
    print(x)
end

A(1)
#prints  2

#made up function
stopsignal!(C)

A(1)
#no longer prints 2
```

**Comment by TsurHerman** [comment]
Pickled Rick!

`detach(C)' should do it.
There is no re-attach function for a signal but it is straight fwd to implement.
```
reattach(s::Signal) = foreach(arg for arg in s.action.args if (arg isa Signal)) do source_signal
    (s ∉ source_signal.children) && push!(source_signal.children,s)
end
```
I'll add it later once I have some time to grok the new registration process, or you can issue a PR

alternatively one can use `when`

**Comment by onetonfoot** [comment]
Thanks, good man
